services:
  postgres:
    image: postgres:17
    container_name: postgres-biblio
    environment:
      POSTGRES_DB: libreria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - libreria-net

  app:
    image: app-biblio:1.0
    container_name: app-biblio
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - libreria-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/libreria 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  pgdata:

networks:
  libreria-net: